### ISSUE TITLE
Design idiomatic pattern for implementation and testing of Mutators

### ISSUE THREAD

**Issue by dhonig** [boomerdigital/solidus_graphql_api#3]
We should review the example mutators and identify good/bad practices.
Currently mutators are only done as integration tests.

We should probably look at this and see if its better done as an integration test.

**Comment by docelic** [comment]
So far I am thinking we can design the tests in a way similar to solidus_api's, which basically means providing GraphQL-specific 1) convenience methods for running the requests and 2) rspec matchers to test the responses.

In terms of making requests themselves, I'll provide two convenience methods:

1) One which uses a full POST or GET request and goes through the GraphQL controller. This will cause the requests to have the correct "context" attached to them when GraphQL executes. (Context is initialized in the controller and currently contains `current_user` and `current_spree_store`.)

2) One which uses `Schema.execute()` directly. This is a direct call avoiding any HTTP or controller action and its context is empty unless manually populated.

However, in practice there will be very little difference between the two methods -- the `context` which is initialized in the controller is the exact same `context` passed to `Schema.execute()`. So it is trivial to populate the context manually with `current_store` (or any other relevant values) and have the requests run as usual.

Comments/additional ideas welcome. Thanks!

**Comment by docelic** [comment]
Ok, further progress here.

First, I confirmed the assumption that in tests it only makes sense to have the expected GraphQL responses/results defined directly in/near the test rather than at the top of the file. Everything else is unusual/inconvenient.

Second, I also realized that (even though GraphQL supports it), it is impractical to keep the GraphQL queries listed in one string at the top of the file. There are two reasons for it:

1. In that case, the input/request and output/desired result are not self-contained in a test
1. Even more important, when queries are kept all in one string and chosen for execution with `operationName` parameter, then GraphQL still checks all queries against the GraphQL schema even if they won't be run. Which means that if any query is invalid, all tests fail because they all use the same big query.

So, with those considerations applied, I am pretty happy with how the generated code now looks:

```
# frozen_string_literal: true
require 'spec_helper'

module Spree::GraphQL
  describe 'Types::Shop' do
    #let!(:shop){ create(:store) }
    #let!(:context){ { current_store: shop } }
    #let!(:variables){ }

    # name: The shop’s name.
    # @return [Types::String!]
    describe 'name' do
      let!(:query) { { shop { name } } }
      let!(:result) { {"data":{"shop":{"name": shop.name}}} }
      #it 'succeeds' do
      #  execute query
      #  expect(response_hash).to eq(result_hash)
      #end
    end

    # description: A description of the shop.
    # @return [Types::String]
    describe 'description' do
      let!(:query) { { shop { description } } }
      let(:result){{"data":{"shop":{"description": shop.meta_description}}}}
      #it 'succeeds' do
      #  execute
      #  expect(response_json).to eq(result_json)
      #end
    end
  end
end
```

A couple things are important to note here:

1. The command to execute queries is just `execute`. It runs `Schema.execute()` with defaulting to `query()`, `context()` and `variables()` unless these params are manually provided.

1. The result which is expected to come from the query can be specified as either Ruby hash or JSON string. JSON is great if a person has the response JSON and just wants to match against it, and Hash is great if one wants to use variables in it and not deal with issues of variable interpolation and quoting within strings, etc.

1. After the query is executed, the result is saved to `@response`/`response()` as usual. Then there are additional helpers defined on it: `response_json` to get JSON string of the response, and `response_hash` to get Ruby hash of the response.

1. Finally, the same `_json` and `_hash` helpers are defined for `result` too. So to match the response with the expected result, one can use either one of these:

```
expect(response_json).to eq(result_json)

expect(response_hash).to eq(result_hash)
```

(The hashes are created with Rails' "indifferent access" to they support both strings and symbols as keys transparently.)

So, all in all pretty good.

The next things to work on from here are:

1) Improve the auto-generated code for mutations. I want the generator to generate basically fully valid mutation query and response templates, and this is a little bit more work than for basic queries because generator needs to support query inputs and response payloads.

2) In addition to `execute` which calls `Schema.execute()` directly, add `post`. Post would accept the same args but performs a HTTP POST and go through the controller. Whether to name it exactly `post` or choose a different/non-taken name

Comments/improvement requests welcome. Thanks!

**Comment by docelic** [comment]
(Still working on this one. I want the tests to be pre-generated with almost complete queries and expected results. Currently at some 45% of that effort.)

**Comment by docelic** [comment]
Coding of the generator is mostly done at this point. Doing final testing before updating the PR.
